name: build
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
    secrets:
      UNITY_USERNAME:
        required: true
      UNITY_PASSWORD:
        required: true
jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: RageAgainstThePixel/unity-setup@v1
        with:
          version-file: 'None'
          unity-version: ${{ matrix.unity-version }}
          build-targets: ${{ matrix.build-target }}
      - uses: ./ # buildalon/action-activate-unity-license
        with:
          license: Personal
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
      - uses: RageAgainstThePixel/unity-action@v2
        timeout-minutes: 10
        with:
          args: '-quit -nographics -batchmode -createProject "${{ github.workspace }}/Test Project"'
