name: validate
on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  push:
    branches: [main]
  pull_request:
    branches: ['*']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    permissions:
      contents: read
    env:
      UNITY_EDITORS: '' # set by the unity-setup action
      UNITY_HUB_PATH: '' # set by the unity-setup action
      UNITY_EDITOR_PATH: '' # set by the unity-setup action
      UNITY_PROJECT_PATH: '' # set by the unity-setup action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        unity-versions: ['5.6.7f1 (e80cc3114ac1)', 2019.x, 2020.x, 2021.x, 2022.x, 6000.x]
        exclude:
          - os: ubuntu-latest
            unity-versions: '5.6.7f1 (e80cc3114ac1)'
    steps:
      - uses: actions/checkout@v4
      - uses: RageAgainstThePixel/unity-setup@v1
        with:
          version-file: None
          unity-version: ${{ matrix.unity-versions }}
          modules: None
      - uses: ./ # RageAgainstThePixel/action-activate-unity-license
        with:
          license: Personal
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
      - uses: RageAgainstThePixel/unity-action@v1
        timeout-minutes: 10
        with:
          args: '-quit -nographics -batchmode -createProject "${{ github.workspace }}/Test Project"'
